11:24:44 | PIX_RPA_MAIN | INFO | üöÄ Inicializando PIX RPA Process
11:24:44 | PIX_RPA_MAIN | INFO | ‚úì Gestores principales inicializados
11:24:44 | PIX_RPA_MAIN | INFO | ‚úì Gestores opcionales inicializados
11:24:44 | PIX_RPA_MAIN | INFO | üöÄ Iniciando proceso PIX RPA
11:24:44 | PIX_RPA_MAIN | INFO | üîç Validando entorno PIX RPA...
11:24:44 | PIX_RPA_MAIN | INFO |   ‚úì Directorio verificado: data/
11:24:44 | PIX_RPA_MAIN | INFO |   ‚úì Directorio verificado: reports/
11:24:44 | PIX_RPA_MAIN | INFO |   ‚úì Directorio verificado: logs/
11:24:44 | PIX_RPA_MAIN | INFO |   ‚úì Directorio verificado: evidencias/
11:24:44 | PIX_RPA_MAIN | INFO |   ‚úì Directorio verificado: config/
11:24:44 | PIX_RPA_MAIN | INFO |   ‚úì Dependencias cr√≠ticas verificadas
11:24:44 | PIX_RPA_MAIN | INFO | ‚úÖ Validaci√≥n de entorno completada
11:24:44 | PIX_RPA_MAIN | INFO | üöÄ PASO 1: Consumo de API p√∫blica
11:24:45 | PIX_RPA_MAIN | INFO | ‚úÖ Productos obtenidos: 20
11:24:45 | PIX_RPA_MAIN | INFO | ‚òÅÔ∏è Subida de JSON a OneDrive deshabilitada o no configurada.
11:24:45 | PIX_RPA_MAIN | INFO | üöÄ PASO 2: Almacenamiento en base de datos
11:24:45 | PIX_RPA_MAIN | INFO | ‚úÖ Productos insertados en BD: 0
11:24:45 | PIX_RPA_MAIN | INFO | üöÄ PASO 3: Generaci√≥n de reporte Excel
11:24:45 | PIX_RPA_MAIN | INFO | ‚úÖ Reporte Excel generado: /home/camper/Descargas/-prueba-t-cnica-RPA--master/PRUEBA-RPA-main/reports/Reporte_2025-09-10.xlsx
11:24:45 | PIX_RPA_MAIN | INFO | üöÄ PASO 4: Subida a OneDrive
11:24:45 | PIX_RPA_MAIN | INFO | ‚òÅÔ∏è OneDrive deshabilitado por configuraci√≥n
11:24:45 | PIX_RPA_MAIN | INFO | üöÄ PASO 5: Automatizaci√≥n web (formulario)
11:24:45 | WDM | INFO | ====== WebDriver manager ======
11:24:45 | WDM | INFO | Get LATEST chromedriver version for google-chrome
11:24:45 | WDM | INFO | Get LATEST chromedriver version for google-chrome
11:24:45 | WDM | INFO | Driver [/home/camper/.wdm/drivers/chromedriver/linux64/134.0.6998.165/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver] found in cache
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ead10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9de0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9f90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea470>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea680>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea3e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eab00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea950>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea0e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eae60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9900>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e91b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb460>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb670>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ebaf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb2e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb280>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e96f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9f30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e94b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9c00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea5c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/elements
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea3e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ebc10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ebe20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eac20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea6b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eac80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ea1a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9ed0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9a50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844e9810>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eafb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844ead10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/element
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eba00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/screenshot
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/screenshot
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb760>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b/screenshot
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eaef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3843400d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b
11:24:54 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eb3844eb820>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1886b31304adc1eef2629332e531db3b
11:24:54 | PIX_RPA_MAIN | WARNING | ‚ö†Ô∏è No se pudo enviar el formulario web
11:24:54 | PIX_RPA_MAIN | INFO | üöÄ PASO 6: Registro de evidencias
11:24:54 | PIX_RPA_MAIN | INFO | ‚úÖ Evidencias registradas en: /home/camper/Descargas/-prueba-t-cnica-RPA--master/PRUEBA-RPA-main/evidencias/evidencia_2025-09-10_11-24-54.json
11:24:54 | PIX_RPA_MAIN | INFO | ================================================================================
11:24:54 | PIX_RPA_MAIN | INFO | üéâ PROCESO PIX RPA FINALIZADO
11:24:54 | PIX_RPA_MAIN | INFO | ‚è±Ô∏è  Tiempo total: 9.76 segundos
11:24:54 | PIX_RPA_MAIN | INFO | üìä Productos procesados: 20
11:24:54 | PIX_RPA_MAIN | INFO | üìÅ Archivos generados: 2
11:24:54 | PIX_RPA_MAIN | INFO | ‚úÖ Pasos completados: 4/6
11:24:54 | PIX_RPA_MAIN | INFO | üìÇ Archivos creados:
11:24:54 | PIX_RPA_MAIN | INFO |    ‚Ä¢ /home/camper/Descargas/-prueba-t-cnica-RPA--master/PRUEBA-RPA-main/data/raw/Productos_2025-09-10.json
11:24:54 | PIX_RPA_MAIN | INFO |    ‚Ä¢ /home/camper/Descargas/-prueba-t-cnica-RPA--master/PRUEBA-RPA-main/reports/Reporte_2025-09-10.xlsx
11:24:54 | PIX_RPA_MAIN | INFO | ================================================================================
